Pipelines:
 QCcontrol
 assemble
 evaluete
 align
 user_define
Tools:
 kmergenie:
  bin:
  options: [""]
 jellyfish:
  bin: 
  options: [""]
 fastqc:
  bin: 
  options: [""]
 trimmomatic:
  bin: 
  options: [""]
 masurca:
  bin: 
  options: [""]
 abyss:
  bin:
  options: [""]
 abyss_mergePairs:
  bin: 
  options: [""]
 soapdenovo:
  bin: 
  options: [""]
 spades:
  bin:
  options: [""]
 cabog:
  bin:
  options: [""]
 FRC:
  bin:
  options: [""]
 CEGMA:
  bin:
  options: [""]
 bwa:
  bin:
  options: [""]
 picard:
  bin:
  options: [""]
 samtools:
  bin:
  options: [""]
 qaTools:
  bin:
  options: [""]
