Pipelines:
 QCcontrol: ["fastqc", "abyss", "trimmomatic", "kmergenie", "align"]
 assemble: ["abyss", "allpaths", "cabog",  "masurca", "soapdenovo", "spades", "trinity"]
 evaluete: ["align", "qaTools", "FRC"]
 align: []
Tools:
 kmergenie:
  bin: /sw/apps/bioinfo/KmerGenie/1.6741/milou/kmergenie
  options: [""]
 fastqc:
  bin: /sw/apps/bioinfo/fastqc/0.11.2/milou/fastqc
  options: [--threads,  "16" ,  --outdir,  fastqc, --extract]
 trimmomatic:
  bin: /proj/a2010002/nobackup/sw/mf/bioinfo-tools/misc/trimmomatic/0.30/trimmomatic-0.30.jar
  options: [""]
 bwa:
  bin: /sw/apps/bioinfo/bwa/0.7.4/milou/bin/bwa
  options: ""
 picard:
  bin: /sw/apps/bioinfo/picard/1.92/milou/
  options: ""
 samtools:
  bin: /sw/apps/bioinfo/samtools/0.1.19/milou/bin/samtools
  options: ""
 abyss:
  bin: /sw/apps/bioinfo/abyss/1.3.5/milou/bin/
  options: [""]
 abyss_mergePairs:
  bin: /sw/apps/bioinfo/abyss/1.3.5/milou/bin/abyss-mergepairs
  options: ["-m 20", "-1 230", "-2 230"]
 allpaths:
  bin: /sw/apps/bioinfo/allpathslg/52485/milou/bin/
  options: ["PLOIDY=2"]
 cabog:
  bin: /sw/apps/bioinfo/cabog/8.1/Linux-amd64/bin/
  options: [""]
 masurca:
  bin: /sw/apps/bioinfo/MaSuRCA/2.3.2/milou/
  options: [""]
 soapdenovo:
  bin: /sw/apps/bioinfo/SOAPdenovo/2.04-r240/milou/bin/SOAPdenovo-63mer
  options: [""]
 spades:
  bin: /sw/apps/bioinfo/spades/3.6.0/milou/bin/spades.py
  options: ["--careful", "-t 8"]
 trinity:
  bin: /sw/apps/bioinfo/trinity/2014-07-17/milou/
  options: []
 FRC:
  bin: /proj/a2010002/nobackup/sw/mf/bioinfo-tools/misc/FRC_align/bin/FRC
  options: ""
 qaTools:
  bin: /proj/a2010002/nobackup/sw/mf/bioinfo-tools/misc/qaTools/qaCompute
  options: ""
